// Checks the shared checkers in js/kitx.js on typical right, wrong and badly formatted answers.  node tests/kitx_test.js
var fs = require('fs'), path = require('path'), vm = require('vm'), root = path.join(__dirname, '..');
var ctx = { console: console, Math: Math, JSON: JSON, Number: Number, String: String, Array: Array, Object: Object, isFinite: isFinite, RegExp: RegExp, Error: Error };
ctx.window = ctx; ctx.globalThis = ctx; vm.createContext(ctx);
['assets/katex/katex.min.js', 'js/core.js', 'js/expr.js', 'js/kit.js', 'js/kitx.js'].forEach(function (f) { vm.runInContext(fs.readFileSync(path.join(root, f), 'utf8'), ctx, { filename: f }); });
var K = ctx.HW.kit, fails = 0, n = 0;
function T(name, chk, resp, want, code) { n++; var r = chk(resp); var okk = r.v === want && (!code || r.code === code); if (!okk) { fails++; console.log('FAIL', name, JSON.stringify(resp), '->', JSON.stringify(r), 'want', want, code || ''); } }
var mix72 = K.radical({ k: 6, n: 2, m: 2 }, 'mixed');
T('mixed ok', mix72, '6\\sqrt{2}', 'correct'); T('mixed plain', mix72, '6sqrt(2)', 'correct'); T('mixed unicode', mix72, '6√2', 'correct');
T('not simplest', mix72, '2\\sqrt{18}', 'form', 'not-simplest'); T('entire given', mix72, '\\sqrt{72}', 'form', 'not-simplest');
T('coef-power', mix72, '36\\sqrt{2}', 'wrong', 'coef-power'); T('divided', mix72, '4\\sqrt{18}', 'wrong', 'divided');
T('decimal', mix72, '8.49', 'form', 'decimal'); T('blank', mix72, '6\\sqrt{\\placeholder{}}', 'form'); T('two roots', mix72, '\\sqrt{36}\\sqrt{2}', 'form', 'one-radical');
T('times', mix72, '6\\times\\sqrt{2}', 'correct'); T('wrong', mix72, '3\\sqrt{2}', 'wrong');
var ent = K.radical({ k: 3, n: 2, m: 5 }, 'entire');
T('entire ok', ent, '\\sqrt{45}', 'correct'); T('entire no-power', ent, '\\sqrt{15}', 'wrong', 'no-power'); T('entire added', ent, '\\sqrt{14}', 'wrong', 'added'); T('entire left', ent, '3\\sqrt{5}', 'form', 'not-entire');
var c3 = K.radical({ k: -2, n: 3, m: 4 }, 'mixed');
T('cube neg', c3, '-2\\sqrt[3]{4}', 'correct'); T('cube neg inside', c3, '2\\sqrt[3]{-4}', 'correct'); T('cube not simplest', c3, '-\\sqrt[3]{32}', 'form', 'not-simplest'); T('cube coef-power', c3, '-8\\sqrt[3]{4}', 'wrong', 'coef-power'); T('cube index', c3, '-2\\sqrt{4}', 'wrong');
var ce = K.radical({ k: -2, n: 3, m: 4 }, 'entire'); T('cube entire', ce, '\\sqrt[3]{-32}', 'correct'); T('cube entire minus out', ce, '-\\sqrt[3]{32}', 'correct');
var fr = K.radical({ k: [1, 3], n: 3, m: 7 }, 'mixed'); T('fraction coef', fr, '\\frac{1}{3}\\sqrt[3]{7}', 'correct'); T('fraction coef2', fr, '\\frac{\\sqrt[3]{7}}{3}', 'correct');
var f = K.fraction([-2, 3]);
T('frac ok', f, '-\\frac{2}{3}', 'correct'); T('frac plain', f, '-2/3', 'correct'); T('frac neg den', f, '\\frac{2}{-3}', 'correct'); T('frac lowest', f, '-\\frac{4}{6}', 'form', 'lowest'); T('frac decimal', f, '-0.\\overline{6}', 'form', 'decimal'); T('frac flip', f, '-\\frac{3}{2}', 'wrong', 'flip'); T('frac sign', f, '\\frac{2}{3}', 'wrong', 'sign');
var rp = K.repeating([1, 6]);
T('rep ok', rp, '0.1\\overline{6}', 'correct'); T('rep long ok', rp, '0.16\\overline{6}', 'correct'); T('rep dots', rp, '0.1666...', 'form', 'dots'); T('rep no bar', rp, '0.1667', 'wrong', 'no-bar'); T('rep wrong block', rp, '0.\\overline{16}', 'wrong', 'bar-block'); T('rep frac', rp, '\\frac{1}{6}', 'form', 'as-decimal');
var term = K.repeating([3, 8]); T('terminating', term, '0.375', 'correct');
var ap = K.approx(Math.sqrt(50), 2);
T('approx ok', ap, '7.07', 'correct'); T('approx long', ap, '7.0710', 'form', 'round'); T('approx places', ap, '7.1', 'form', 'places'); T('approx wrong', ap, '7.08', 'wrong');
var ap2 = K.approx(4 * Math.cbrt(11), 2); T('approx trunc', K.approx(2.678, 2), '2.67', 'wrong', 'truncate'); T('approx ok2', ap2, (Math.round(4 * Math.cbrt(11) * 100) / 100).toFixed(2), 'correct');
var o = K.order(['a', 'b', 'c']); T('order ok', o, ['a', 'b', 'c'], 'correct'); T('order partial', o, ['a'], 'form'); T('order wrong', o, ['b', 'a', 'c'], 'wrong');
var g = K.grid({ r1: ['N', 'W'], r2: [] }); T('grid ok', g, { r1: ['W', 'N'], r2: [] }, 'correct'); T('grid wrong', g, { r1: ['W'], r2: [] }, 'wrong'); T('grid empty', g, {}, 'form');
var gs = K.grid({ r1: 'a', r2: 'b' }); T('grid single', gs, { r1: 'a', r2: 'b' }, 'correct'); T('grid single incomplete', gs, { r1: 'a' }, 'form');
var v = K.value([3, 4], { only: 'fraction' }); T('value frac', v, '\\frac{3}{4}', 'correct'); T('value unsimplified', v, '\\frac{6}{8}', 'form'); T('value sqrt', v, '\\sqrt{\\frac{9}{16}}', 'form');
var vr = K.varRadical('2x\\sqrt{3x}', 'mixed');
T('var ok', vr, '2x\\sqrt{3x}', 'correct'); T('var not simplest', vr, '\\sqrt{12x^{3}}', 'form'); T('var not simplest2', vr, '2\\sqrt{3x^{3}}', 'form', 'not-simplest-var'); T('var wrong', vr, '2x^{2}\\sqrt{3x}', 'wrong');
var ve = K.varRadical('\\sqrt{12x^{3}}', 'entire'); T('var entire', ve, '\\sqrt{12x^3}', 'correct'); T('var entire left', ve, '2x\\sqrt{3x}', 'form', 'not-entire');
T('mixed number frac', K.fraction([7, 2]), '3\\frac{1}{2}', 'form', 'mixed-num'); T('mixed number wrong', K.fraction([7, 2]), '3\\frac{1}{4}', 'wrong'); T('improper ok', K.fraction([7, 2]), '\\frac{7}{2}', 'correct');
T('mixed neg', K.value([-7, 2]), '-3\\frac{1}{2}', 'form', 'mixed-num');
T('rad product coef', mix72, '2\\times 3\\sqrt{2}', 'form', 'simplify'); T('rad unreduced frac', K.radical({ k: -2, n: 2, m: 2 }, 'mixed'), '\\frac{-4\\sqrt{2}}{2}', 'form', 'simplify');
T('rad frac coef ok', K.radical({ k: [3, 4], n: 2, m: 2 }, 'mixed'), '\\frac{3\\sqrt{2}}{4}', 'correct'); T('integer as product', K.radical({ k: -26, n: 1, m: 1 }, 'mixed'), '-\\frac{1}{3}\\times 78', 'form', 'simplify'); T('integer ok', K.radical({ k: -26, n: 1, m: 1 }, 'mixed'), '-26', 'correct');
var ne = K.radical({ k: -2, n: 4, m: 7 }, 'entire'); T('neg even entire', ne, '-\\sqrt[4]{112}', 'correct'); T('neg even inside rejected', ne, '\\sqrt[4]{-112}', 'wrong');
var e1 = K.expo('\\frac{432r^{4}}{p^{14}q^{5}}');
T('expo ok', e1, '\\frac{432r^4}{p^{14}q^5}', 'correct'); T('expo ok order', e1, '\\frac{432r^{4}}{q^{5}p^{14}}', 'correct'); T('expo plain', e1, '432r^4/(p^14 q^5)', 'correct');
T('expo neg', e1, '432r^{4}p^{-14}q^{-5}', 'form', 'neg-exp'); T('expo wrong exp', e1, '\\frac{432r^{4}}{p^{12}q^{5}}', 'wrong', 'exp'); T('expo coef', e1, '\\frac{216r^{4}}{p^{14}q^{5}}', 'wrong', 'coef');
T('expo flip', e1, '\\frac{432}{r^{4}p^{14}q^{5}}', 'wrong', 'flip-exp');
var e2 = K.expo('-\\frac{1}{3}x^{5}z^{2}');
T('expo frac coef', e2, '-\\frac{1}{3}x^5z^2', 'correct'); T('expo frac coef2', e2, '-\\frac{x^{5}z^{2}}{3}', 'correct'); T('expo unreduced', e2, '-\\frac{2x^{5}z^{2}}{6}', 'form', 'coef');
T('expo combine', e2, '-\\frac{1}{3}x^{3}x^{2}z^{2}', 'form', 'combine'); T('expo brackets', e2, '-\\frac{1}{3}\\left(x^{5}\\right)z^{2}', 'correct');
var e3 = K.expo('81m^{18}n^{22}'); T('expo nested', e3, '\\left(3m^{9}n^{11}\\right)^{2}\\cdot 9', 'form'); T('expo numpow', e3, '3^{4}m^{18}n^{22}', 'form', 'evaluate'); T('expo sign', e3, '-81m^{18}n^{22}', 'wrong', 'sign');
var e4 = K.expo('7^{2}', { evaluate: false }); T('expo keep power', e4, '7^2', 'correct'); T('expo keep power 49', e4, '49', 'correct');
var e5 = K.expo('z^{\\frac{5}{6}}', { form: 'power' }); T('expo rational', e5, 'z^{\\frac{5}{6}}', 'correct'); T('expo rational radical', e5, '\\sqrt[6]{z^5}', 'form', 'not-power'); T('expo rational slash', e5, 'z^(5/6)', 'correct');
var e6 = K.expo('\\sqrt[3]{p^{2}}', { form: 'radical' }); T('expo radical ok', e6, '\\sqrt[3]{p^2}', 'correct'); T('expo radical alt', e6, '\\left(\\sqrt[3]{p}\\right)^{2}', 'correct'); T('expo radical power', e6, 'p^{\\frac{2}{3}}', 'form', 'not-radical');
var e7 = K.expo('4096^{\\frac{1}{6}}', { form: 'single-power', evaluate: false }); T('single power', e7, '4096^{\\frac{1}{6}}', 'correct'); T('single power value', e7, '4', 'form', 'single-power');
var e8 = K.expo('a^{4x+3y}'); T('var exponent', e8, 'a^{4x+3y}', 'correct'); T('var exponent wrong', e8, 'a^{4x+2y}', 'wrong');
var e9 = K.expo('\\frac{1}{16}'); T('numeric', e9, '\\frac{1}{16}', 'correct'); T('numeric power', e9, '2^{-4}', 'form'); T('numeric decimal', e9, '0.0625', 'correct');
var s1 = K.sci(32000); T('sci ok', s1, '3.2\\times10^{4}', 'correct'); T('sci std', s1, '32000', 'form', 'not-sci'); T('sci range', s1, '32\\times10^{3}', 'form', 'coef-range'); T('sci off', s1, '3.2\\times10^{5}', 'wrong', 'power-off');
var s2 = K.sci(0.000453, { sig: 2 }); T('sci small sig', s2, '4.5\\times10^{-4}', 'correct'); T('sci sig long', s2, '4.53\\times10^{-4}', 'form', 'sig');
var sx = K.sci(2.4e-16); T('sci tiny ok', sx, '2.4\\times10^{-16}', 'correct'); T('sci tiny off', sx, '2.4\\times10^{-17}', 'wrong'); T('sci e-notation', sx, '2.4e-16', 'form', 'e-notation');
var ve = K.expo('\\frac{r^{2n}}{s^{6n}}'); T('neg sym exp', ve, 'r^{2n}s^{-6n}', 'form', 'neg-exp'); T('sym ok', ve, '\\frac{r^{2n}}{s^{6n}}', 'correct');
var vz = K.expo('z^{7}'); T('exp letter cancels', vz, '\\frac{z^{2n+7}}{z^{2n}}', 'form', 'combine');
// MathLive writes one-digit fractions without braces: \frac59
T('compact frac', K.fraction([5, 9]), '\\frac59', 'correct'); T('compact neg frac', K.fraction([-2, 3]), '-\\frac23', 'correct'); T('compact mixed', K.fraction([7, 3]), '2\\frac13', 'form', 'mixed-num');
T('compact frac expo', K.expo('\\frac{3x^{4}}{7}'), '\\frac37x^4', 'correct');
T('compact frac exponent', K.expo('x^{\\frac{2}{3}}'), 'x^{\\frac23}', 'correct'); T('compact radical frac', K.radical({ k: [1, 2], n: 2, m: 3 }, 'mixed'), '\\frac12\\sqrt3', 'correct');
console.log(n + ' checks, ' + fails + ' failed'); process.exit(fails ? 1 : 0);
